daliyflash-day-11.20/apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartView,CartAddView,CartUpdateView,CartDelView

urlpatterns = [
    url(r'^add$',CartAddView.as_view(),name='cart_add'),
    url(r'^update$',CartUpdateView.as_view(),name='cart_update'),
    url(r'^del$',CartDelView.as_view(),name='cart_del'),
    url(r'^$',CartView.as_view(),name='cart_show'),


]

daliyflash-day-11.20/apps/order/urls.py
from django.conf.urls import url
from order.views import PlaceOrderView,CommitOrderView,PayOrderView,CheckOrderView,CommentOrderView

urlpatterns = [
    url(r'^place_order$',PlaceOrderView.as_view(),name='place_order'),
    url(r'^commit_order$',CommitOrderView.as_view(),name='commit_order'),
    url(r'^pay_order$',PayOrderView.as_view(),name='pay_order'),
    url(r'^order_check$',CheckOrderView.as_view(),name='order_check'),
    url(r'^order_comment/(?P<order_id>.+)$',CommentOrderView.as_view(),name='order_comment'),
]

daliyflash-day-11.20/daliyflash/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^user/', include('user.urls', namespace='user')),  # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
    url(r'^search', include('haystack.urls')),  # 搜索引擎
    url(r'^', include('goods.urls', namespace='goods')),  # 商品模块
]

daliyflash-day-11.20/apps/cart/models.py
from django.db import models

# Create your models here.

daliyflash-day-11.20/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from utils.mixin import LoginRequiredMixin
from django.http import JsonResponse
from goods.models import GoodSKU
from django_redis import get_redis_connection
# Create your views here.

class CartView(LoginRequiredMixin,View):
    '''购物车视图类'''
    def get(self,request):
        '''显示购物车页面'''
        #redis数据库获取购物车信息
        #1、连接数据库
        conn = get_redis_connection('default')
        user = request.user
        cart_key = 'cart_%d'%user.id
        cart_dict = conn.hgetall(cart_key)
        skus = []
        total_count = 0
        total_amount = 0
        for sku_id ,count in cart_dict.items():
            sku = GoodSKU.objects.get(id = sku_id)
            amount = sku.price*int(count)
            sku.count = count
            sku.amount = amount
            skus.append(sku)

            total_count += int(count)
            total_amount += amount

        context ={
            'skus':skus,
            'total_count':total_count,
            'total_amount':total_amount,
        }

        return render(request,'cart/cart.html',context)

class CartAddView(View):
    '''添加购物车视图类 '''
    def post(self,request):
        '''添加购物车业务'''
        #登录判断,因为用的是ajax提交的所以不能用登录装饰器
        user = request.user
        if not user.is_authenticated():
            #用户未登录
            context = {
                'res':1,
                'errmsg':'请先登录'
            }
            return JsonResponse(context)
        #获取数据
        sku_id = request.POST.get('cart_id')
        sku_count = request.POST.get('count')
        #数据校验
        #1、校验数据完整性
        if not all([sku_id,sku_count]):
            context = {
                'res':2,
                'errmsg':'数据不完整'
            }
            return JsonResponse(context)
        #2、校验商品id是否存在
        try:
            sku = GoodSKU.objects.get(id = sku_id)
        except GoodSKU.DoesNotExist:
            context ={
                'res':3,
                'errmsg':'商品地不存在',
            }
            return JsonResponse(context)
        #3、检验商品数量是否是数字
        try:
            count = int(sku_count)
        except Exception  as e:
            context ={
                'res':4,
                'errmsg':'商品数量不合法'
            }
            return JsonResponse(context)
        #业务处理：向redis数据库中添加购物车记录
        #连接redis数据库
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        cart_count = conn.hget(cart_key,sku.id)
        if cart_count:
            count += int(cart_count)
        if count > sku.stock:
            context = {
                'res':5,
                'errmsg':'库存不足',
            }
            return  JsonResponse(context)
        conn.hset(cart_key,sku_id,count)

        total_count = conn.hlen(cart_key)
        context = {
            'res':6,
            'total_count':total_count,
            'message':'添加成功'
        }
        #返回json数据对象
        return JsonResponse(context)


class CartUpdateView(View):
    '''购物车更新视图类'''
    def post(self,request):
        '''添加购物车业务'''
        # 登录判断,因为用的是ajax提交的所以不能用登录装饰器
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            context = {
                'res': 1,
                'errmsg': '请先登录'
            }
            return JsonResponse(context)
        # 获取数据
        sku_id = request.POST.get('cart_id')
        sku_count = request.POST.get('count')
        # 数据校验
        # 1、校验数据完整性
        if not all([sku_id, sku_count]):
            context = {
                'res': 2,
                'errmsg': '数据不完整'
            }
            return JsonResponse(context)
        # 2、校验商品id是否存在
        try:
            sku = GoodSKU.objects.get(id=sku_id)
        except GoodSKU.DoesNotExist:
            context = {
                'res': 3,
                'errmsg': '商品地不存在',
            }
            return JsonResponse(context)
        # 3、检验商品数量是否是数字
        try:
            count = int(sku_count)
        except Exception  as e:
            context = {
                'res': 4,
                'errmsg': '商品数量不合法'
            }
            return JsonResponse(context)
        # 业务处理：向redis数据库中添加购物车记录
        # 连接redis数据库
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # cart_count = conn.hget(cart_key, sku.id)
        # if cart_count:
        #     count += int(cart_count)
        if count > sku.stock:
            context = {
                'res': 5,
                'errmsg': '库存不足',
            }
            return JsonResponse(context)
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        context = {
            'res':6,
            'total_count':total_count,
            'message':'更新成功',
        }
        return JsonResponse(context)


class CartDelView(View):
    '''删除购物车记录视图'''
    def post(self,request):
        '''业务'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            context = {
                'res': 1,
                'errmsg': '请先登录'
            }
            return JsonResponse(context)
        # 获取数据
        sku_id = request.POST.get('cart_id')

        # 数据校验
        # 1、校验数据完整性
        if not sku_id:
            context = {
                'res': 2,
                'errmsg': '无效商品'
            }
            return JsonResponse(context)
        # 2、校验商品id是否存在
        try:
            sku = GoodSKU.objects.get(id=sku_id)
        except GoodSKU.DoesNotExist:
            context = {
                'res': 3,
                'errmsg': '商品地不存在',
            }
            return JsonResponse(context)

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        context = {
            'res':4,
            'total_count':total_count,
            'message':'删除成功'
        }
        return JsonResponse(context)

daliyflash-day-11.20/templates/cart/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}
	天天生鲜-购物车
{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/cart.js' %}"></script>
{% endblock topfiles %}
{% block page_title %}
    购物车
{% endblock page_title %}
{% block body %}

	<!-- 主体 -->
	<div class="total_count">
		全部商品<em>{{ total_count }}</em>件
	</div>

	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="{% url 'order:place_order' %}" method="post">
        {% csrf_token %}
        {% for sku in skus %}
	        <ul class="cart_list_td clearfix">
                <li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
                <li class="col02"><img src="{{ sku.image.url }}"></li>
                <li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
                <li class="col04">{{ sku.unite }}</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">
                    <div class="num_add">

                        <a class="add fl" href="javascript:;" sku_id="{{ sku.id }}" repertory="{{ sku.stock }}" >+</a>
                        <input type="text" class="num_show fl" value="{{ sku.count }}">
                        <a href="javascript:;" class="minus fl" sku_id="{{ sku.id }}" repertory="{{ sku.stock }}">-</a>
                    </div>
                </li>
                <li class="col07">{{ sku.amount }}元</li>
                <li class="col08"><a href="javascript:;">删除</a></li>
	        </ul>
        {% empty %}
            <ul class="cart_list_td clearfix">
                <li class="cart_no_goods">
                    空空如也
                </li>
            </ul>
	    {% endfor %}

        <ul class="settlements">
            <li class="col01"><input type="checkbox" name="" checked=""></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_amount }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
            <li class="col04"><input type="submit" value="去结算" class="place"></li>
        </ul>
    </form>
{% endblock body %}
