daliyflash-day-11.20/apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView,DetailView,ListView

urlpatterns = [
    url(r'^index$',IndexView.as_view(),name='index'),
    url(r'^goods/(?P<goods_id>\d+)$',DetailView.as_view(),name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list'),
]

daliyflash-day-11.20/apps/user/urls.py
from django.conf.urls import url
from apps.user import views
from django.contrib.auth.decorators import login_required
from user.views import RegisterView,ActiveView,LoginView,UserInfoView,UserOrderView,AddressView,LogoutView,AddAddressView
urlpatterns = [
    #url(r'^register$',views.register,name = 'register'),
    #url(r'^register_handle$',views.register_handle,name='register_handle'),
    url(r'^register$',RegisterView.as_view(),name = 'register'),
    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name = 'active'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout',LogoutView.as_view(),name='logout'),

   # url(r'^$',login_required(UserInfoView.as_view()),name = 'user' ),
    #url(r'^order',login_required(UserOrderView.as_view()) ,name = 'order'),
    #url(r'^address',login_required(AddressView.as_view()) ,name='address'),
    url(r'^$',UserInfoView.as_view(),name = 'user' ),
    url(r'^order/(?P<page>\d+)$',UserOrderView.as_view() ,name = 'order'),
    url(r'^address$',AddressView.as_view() ,name='address'),
    url(r'^add_address$',AddAddressView.as_view() ,name='addaddress'),

]

daliyflash-day-11.20/daliyflash/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^user/', include('user.urls', namespace='user')),  # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
    url(r'^search', include('haystack.urls')),  # 搜索引擎
    url(r'^', include('goods.urls', namespace='goods')),  # 商品模块
]

daliyflash-day-11.20/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel
# Create your models here.


class User(AbstractUser, BaseModel):
    '''用户模型类'''

    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

class AddressManager(models.Manager):
    '''地址模型管理器类'''
    def get_default_address(self,user):
        '''获取某用户默认地址'''
        try:
            address = self.get(user = user,is_default=True)
        except self.model.DoesNotExist:
            address = None
        return address

    def get_id_address(self,addr_id):
        '''获取某用户默认地址'''
        try:
            address = self.get(id = addr_id)
        except  self.model.DoesNotExist|self.model.MultipleObjectsReturned:
            address = None
        return address

class Address(BaseModel):
    '''地址模型类'''
    user = models.ForeignKey('User', verbose_name='所属账户')
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    #实例化自定义模型管理器类对象
    objects = AddressManager()

    class Meta:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

daliyflash-day-11.20/apps/user/views.py
from django.shortcuts import render,redirect
from  django.core.urlresolvers import reverse
from django.views.generic import View
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from  itsdangerous import SignatureExpired
from django.core.mail import send_mail
from daliyflash import settings
from django.http import HttpResponse
from celery_tasks.tasks import send_register_active_email
from django.contrib.auth import authenticate,login,logout
from utils.mixin import LoginRequiredMixin
import re
from user.models import User,Address
from goods.models import  GoodSKU
from order.models import OrderInfo,OrderGoods
from django_redis import get_redis_connection
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# Create your views here.
def register(request):
    '''显示注册页面'''
    if request.method =='GET':

        return render(request,'user/register.html')
    else:
        return register_handle(request)


def register_handle(request):
    '''注册业务'''
    #1、接受数据
    t_userName = request.POST.get('user_name')
    t_userPwd = request.POST.get('pwd')
    t_userEmail = request.POST.get('email')
    t_userAllow = request.POST.get('allow')
    #2、数据校验
    #2.1、数据完整性校验
    if not all([t_userName,t_userPwd,t_userEmail]):
        return render(request,'user/register.html',{'errmsg':'数据不完整'})
    # 2.2、邮箱校验
    if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', t_userEmail):
        return render(request, 'user/register.html', {'errmsg': '邮箱格式不正确'})
    #2.3、同意校验
    if t_userAllow !='on':
        return render(request,'user/register.html',{'errmsg':'请同意协议'})
    #2.4、用户名是否存在校验
    try:
        user = User.objects.get(username = t_userName)
    except User.DoesNotExist:
        user = None
    if user:
        # 用户名已存在
        return render(request, 'user/register.html', {'errmsg': '用户名已存在'})
    #3、业务处理：注册
    #3.1、 将数据插入数据库
    user = User.objects.create_user(t_userName, t_userEmail, t_userPwd)
    #3.2、将该用户改成非激活状态
    user.is_active = 0
    user.save()
    #3.3、发送激活码到注册的邮箱
    #3.3.1、生成token
    serializer = Serializer(settings.SECRET_KEY,3600)
    info = {'confirm':user.id}
    token = serializer.dumps(info)
    token = token.decode('utf-8')
    #3.3.2发送激活码
    subject = '天天生鲜欢迎信息'
    message = ''
    sender = settings.EMAIL_FROM
    receiver =[t_userEmail]
    html_message ='<h1>%s,欢迎您成为天天生鲜注册会员</h1>请点击下面的链接激活你的账户</br><a href ="http://192.168.17.131:8000/user/active/%s">http://192.168.17.131:8000/user/active/%s</a>'%(t_userName,token,token)
    send_mail(subject,message,sender,receiver,html_message = html_message)
    #4、返回响应
    return redirect(reverse('goods:index'))


class RegisterView(View):
    '''注册视图'''
    def get(self,request):
        return render(request, 'user/register.html')

    def post(self,request):
        '''注册业务'''
        # 1、接受数据
        t_userName = request.POST.get('user_name')
        t_userPwd = request.POST.get('pwd')
        t_userEmail = request.POST.get('email')
        t_userAllow = request.POST.get('allow')
        # 2、数据校验
        # 2.1、数据完整性校验
        if not all([t_userName, t_userPwd, t_userEmail]):
            return render(request, 'user/register.html', {'errmsg': '数据不完整'})
        # 2.2、邮箱校验
        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', t_userEmail):
            return render(request, 'user/register.html', {'errmsg': '邮箱格式不正确'})
        # 2.3、同意校验
        if t_userAllow != 'on':
            return render(request, 'user/register.html', {'errmsg': '请同意协议'})
        # 2.4、用户名是否存在校验
        try:
            user = User.objects.get(username=t_userName)
        except User.DoesNotExist:
            user = None
        if user:
            # 用户名已存在
            return render(request, 'user/register.html', {'errmsg': '用户名已存在'})
        # 3、业务处理：注册
        user = User.objects.create_user(t_userName, t_userEmail, t_userPwd)
        user.is_active = 0
        user.save()
        # 3.3、发送激活码到注册的邮箱
        # 3.3.1、生成token
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {'confirm': user.id}
        token = serializer.dumps(info)
        token = token.decode('utf-8')
        # 3.3.2发送激活码
        #subject = '天天生鲜欢迎信息'
        #message = ''
        #sender = settings.EMAIL_FROM
        #receiver = [t_userEmail]
        #html_message = '<h1>%s,欢迎您成为天天生鲜注册会员</h1>请点击下面的链接激活你的账户</br><a href ="http://192.168.17.131:8000/user/active/%s">http://192.168.17.131:8000/user/active/%s</a>' % (
        #t_userName, token, token)
        #send_mail(subject, message, sender, receiver, html_message=html_message)
        send_register_active_email.delay(t_userEmail,t_userName,token)
        # 4、返回响应
        return redirect(reverse('goods:index'))



class ActiveView(View):
    '''用户激活业务'''
    def get(self,request,token):
        #解密
        try:
            serializer = Serializer(settings.SECRET_KEY, 3600)
            info = serializer.loads(token)
            #修改数据库
            t_userId = info['confirm']
            user = User.objects.get(id = t_userId)
            user.is_active =1
            user.save()
            return redirect(reverse('user:login'))
        except SignatureExpired as e:
            return HttpResponse('激活链接已过期')



class LoginView(View):
    '''登录业务'''
    def get(self,request):
        '''显示登录页'''
        # 判断是否记住了用户名
        if 'username' in request.COOKIES:
            username = request.COOKIES.get('username')
            checked = 'checked'
        else:
            username = ''
            checked = ''

        return render(request, 'user/login.html', {'username':username, 'checked':checked})

    def post(self,request):
        '''登录验证'''
        #1、接收数据
        t_userName = request.POST.get('username')
        t_userPwd = request.POST.get('pwd')
        t_userRemember = request.POST.get('remember')
        #2、数据校验
        #在前端已经做了这一步
        #3、业务处理：登录验证
        user = authenticate(username=t_userName, password=t_userPwd)
        if user is not None:
            # the password verified for the user
            if user.is_active:
                #print("User is valid, active and authenticated")
                #记录登录状态到session
                login(request,user)
                next_url = request.GET.get('next',reverse('goods:index'))
                response = redirect(next_url)
                #判断是否记住用户名
                if t_userRemember == 'on':
                    response.set_cookie('username',t_userName,max_age=7*3600*24)
                else:
                    response.delete_cookie('username')

                return response
            else:
                #print("The password is valid, but the account has been disabled!")
                return render(request, 'user/login.html', {'errmsg': '用户未激活'})
        else:
            # the authentication system was unable to verify the username and password
            #print("The username and password were incorrect.")
            return render(request, 'user/login.html', {'errmsg': '用户名密码不正确'})
        #4、返回响应


class LogoutView(View):
    '''退出登录视图类'''
    def get(self,request):
        '''显示首页'''
        #清除session
        logout(request)
        return redirect(reverse('goods:index'))


class UserInfoView(LoginRequiredMixin,View):
    '''用户个人信息视图类'''

    def get(self,request):
        '''用户个人信息显示'''
        #page = 'user'
        #1、获取用户的基本信息
        user = request.user
        # try:
        #     address = Address.objects.get(user = user,is_default=True)
        # except Address.DoesNotExist:
        #     address = None

        address = Address.objects.get_default_address(user)
        #username  = user.username
        #addr = address.addr
        #phone = address.phone

        #2、获取用户最近浏览记录
        # from redis import StrictRedis
        # sr = StrictRedis(host='172.16.179.130', port='6379', db=9)
        con = get_redis_connection('default')

        history_key = 'history_%d' % user.id

        # 获取用户最新浏览的5个商品的id
        sku_ids = con.lrange(history_key, 0, 4)  # [2,3,1]

        # 从数据库中查询用户浏览的商品的具体信息
        # goods_li = GoodsSKU.objects.filter(id__in=sku_ids)
        #
        # goods_res = []
        # for a_id in sku_ids:
        #     for goods in goods_li:
        #         if a_id == goods.id:
        #             goods_res.append(goods)

        # 遍历获取用户浏览的商品信息
        goods_li = []
        for id in sku_ids:
            goods = GoodSKU.objects.get(id=id)
            goods_li.append(goods)

        # 组织上下文
        context = {'page': 'user',
                   'address': address,
                   'goods_li': goods_li}

        #3、返回响应
        return render(request,'user/user_center_info.html',context)


class UserOrderView(LoginRequiredMixin, View):
    '''用户订单视图类'''

    def get(self, request,page):
        '''用户订单显示'''
        #获取订单信息
        user = request.user

        orders = OrderInfo.objects.filter(user = user).order_by('-create_time')

        if not  orders:
            # return redirect(reverse('cart:cart_show'))
            return  render(request,'user/user_center_order.html',{'page':'order'})
        for order in orders:
            #获取order_goods信息并添加到订单属性中
            order_goods = OrderGoods.objects.filter(order = order.order_id)
            for order_sku in order_goods:
                # 计算小计
                amount = order_sku.count * order_sku.price
                # 动态给order_sku增加属性amount,保存订单商品的小计
                order_sku.amount = amount
            # 动态给order增加属性，保存订单状态标题
            order.status_name = OrderInfo.ORDER_STATUS[order.order_status]
            order.order_goods = order_goods

        #分页
        paginator = Paginator(orders, 2)
        # 判断用户传进来的页码是否有效
        try:
            orders_page = paginator.page(page)

        except PageNotAnInteger:
            orders_page = paginator.page(1)
        except EmptyPage:
            orders_page = paginator.page(paginator.num_pages)

        # 页码控制，让其只显示5个页码，显示当前夜前两个和当前页以及当前页的夜
        try:

daliyflash-day-11.20/templates/user/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    天天生鲜-登录
{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/msgbox.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}
{% endblock header_con %}
{% block search_bar %}
{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">
		<a class="login_logo" href="{% url 'goods:index' %}"><img src="{% static 'images/logo02.png' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr ">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input ">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>

		</div>

	</div>

{% endblock body %}
{% block bottom %}
<div class="pop_con">
    {% if errmsg == '用户未激活' or errmsg == '用户名密码不正确' %}
        <div class="pop">
            <h2>错误消息</h2>
            <p class="errmsg">{{ errmsg }}</p>
        </div>
        <div class="mask"></div>
    {% endif %}
</div>
{% endblock bottom %}

daliyflash-day-11.20/templates/user/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    天天生鲜-注册
{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/register.js' %}"></script>
    <script type="text/javascript" src = "{% static 'js/msgbox.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}
{% endblock header_con %}
{% block search_bar %}
{% endblock search_bar %}
{% block body %}
    <!-- 注册盒子 -->
	<div class="register_con">

		<!-- div.l_con>a.reg_logo+div.reg_slogan+div.reg_banner -->
		 <div class="l_con fl">
		 	<a class="reg_logo" href="{% url 'goods:index' %}"><img src="{% static 'images/logo02.png' %}"></a>
		 	<div class="reg_slogan">足不出户·新鲜每一天</div>
		 	<div class="reg_banner"></div>
		 </div>

		 <div class="r_con fr">
		 	<div class="reg_title clearfix">
		 		<h1 >用户注册</h1>
		 		<a href="{% url 'user:login' %}">登录</a>
		 	</div>
		 	<div class="reg_form">
		 		<form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
		 			<ul>
		 				<li>
		 					<label>用户名：</label>
		 					<input type="text" name="user_name" id ="user_name">
		 					<span class="error_tip">提示信息</span>
		 				</li>
		 				<li>
		 					<label>密码：</label>
		 					<input type="password" name="pwd" id ="pwd">
		 					<span class="error_tip">提示信息</span>

		 				</li>
		 				<li>
		 					<label>确认密码：</label>
		 					<input type="password" name="cpwd" id ="cpwd">
		 					<span class="error_tip">提示信息</span>
		 				</li>
		 				<li>
		 					<label>邮箱：</label>
		 					<input type="text" name="email" id ="email">
		 					<span class="error_tip">提示信息</span>
		 				</li>
		 				<li class="agreement">
		 					<input type="checkbox" name="allow" id="allow" checked="checked">
							<label>同意”天天生鲜用户使用协议“</label>
							<span class="error_tip2">提示信息</span>
		 				</li>
		 				<li class="reg_sub">
		 					<input type="submit" value="注 册" name="">
		 				</li>
		 			</ul>
		 		</form>
                <span class="error_tip">{{ errmsg }}</span>
		 	</div>

		 </div>
	</div>

{% endblock body %}

{% block bottom %}
<div class="pop_con">
    {% if errmsg == '用户名已存在' %}
        <div class="pop">
            <h2>错误消息</h2>
            <p class="errmsg">{{ errmsg }}</p>
        </div>
        <div class="mask"></div>
    {% endif %}
</div>
{% endblock bottom %}

daliyflash-day-11.20/templates/user/user_center_add_site.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/msgbox.js' %}"></script>
{% endblock topfiles %}
{% block right_menu_con %}
    <div class="right_menu_con clearfix">

        <h3 class="common_title2">编辑地址</h3>
        <div class="site_con">
            <form method="post">
                {% csrf_token %}
                <div class="form_group">
                    <label>收件人：</label>
                    <input type="text" name="receiver" value="{{ receiver }}">
                </div>
                <div class="form_group form_group2">
                    <label>详细地址：</label>
                    <textarea class="site_area" name="addr" >{{ address }}</textarea>
                </div>
                <div class="form_group">
                    <label>邮编：</label>
                    <input type="text" name="zip_core" value="{{ zip_core }}">
                </div>
                <div class="form_group">
                    <label>手机：</label>
                    <input type="text" name="phone" value="{{ phone }}">
                </div>
                <div class="default_addr clearfix">
                    <input type="checkbox" name="default_addr" {{ default_addr }}>
                    <label>设为默认地址：</label>

                </div>
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>


{% endblock right_menu_con %}
{% block bottom %}
<div class="pop_con">
    {% if errmsg == '数据不完整' or errmsg == '手机格式不正确' %}
        <div class="pop">
            <h2>错误消息</h2>
            <p class="errmsg">{{ errmsg }}</p>
        </div>
        <div class="mask"></div>
    {% endif %}
</div>
{% endblock bottom %}

daliyflash-day-11.20/templates/user/user_center_info.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_menu_con %}
    <div class="right_menu_con clearfix">
			<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
				<ul class="user_info_list clearfix">
					<li>
						<span>用户名：</span>
						<em>{{ user.username }}</em>
					</li>
                    {% if address %}
                        <li>
                            <span>联系方式：</span>
                            <em>{{ address.phone }}</em>
                        </li>
                        <li>
                            <span>联系地址：</span>
                            <em>{{ address.addr }}</em>
                        </li>
                    {% else %}
                        <li>
                            <span>联系方式：</span>
                            <em>无默认地址</em>
                        </li>
                        <li>
                            <span>联系地址：</span>
                            <em>无默认地址</em>
                        </li>
                    {% endif %}
				</ul>
			</div>
			<h3 class=" common_title2">最近浏览</h3>
			<div class="has_view_list">
				<ul class="goods_type_list clearfix">
                    {% for goods in goods_li %}
					<li>
						<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{{ goods.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
						<div class="operate">
							<span class="prize">￥{{ goods.price }}</span>
							<span class="uint">{{ goods.price }}/{{ goods.unite }}</span>
{#							<a href="#" class="add_goods" title="加入购物车"></a>#}
						</div>
					</li>
                    {% empty %}
                    无历史浏览记录
                    {% endfor %}


				</ul>
			</div>
		</div>
{% endblock right_menu_con %}

daliyflash-day-11.20/templates/user/user_center_order.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/user_center_order.js' %}"></script>
{% endblock topfiles %}
{% block right_menu_con %}
    <div class="right_menu_con clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% csrf_token %}
        {% for order in orders_page %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status_name }}</li>
            </ul>

            <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="55%">
                            {% for order_goods in order.order_goods %}
                                <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="{{ order_goods.sku.image.url }}"></li>
                                <li class="col02">{{ order_goods.sku.name }}<em>{{ order_goods.price }}/{{ order_goods.sku.unite }}</em></li>
                                <li class="col03">{{ order_goods.count }}</li>
                                <li class="col04">{{ order_goods.amount }}元</li>
                            </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_price }}元</td>
                        <td width="15%">{{ order.status_name }}</td>
                        <td width="15%">
                            <a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">{% if order.order_status == 1 %}去付款{% elif order.order_status == 4 %}去评价{% else %}查看评价{% endif %}</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        {% empty %}
            <p class="user_no_order">用户还未下订单</p>
        {% endfor %}

        {% if orders_page.paginator.num_pages > 1 %}
            <div class="pagenation">
                {% if orders_page.has_previous %}
                    <a href="{% url 'user:order' orders_page.previous_page_number %}">上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == orders_page.number %}
                    <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
                    {% else %}
                    <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if orders_page.has_next %}
                    <a href="{% url 'user:order' orders_page.next_page_number %}">下一页></a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock right_menu_con %}


daliyflash-day-11.20/templates/user/user_center_order_comment.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}

{% block right_menu_con %}
    <div class="right_menu_con clearfix">
        <h3 class="common_title2">全部订单</h3>
        <ul class="order_list_th w978 clearfix">
            <li class="col01">{{ order.create_time }}</li>
            <li class="col02">订单号：{{ order.order_id }}</li>
            <li class="col02 stress">{{ order.status_name }}</li>
        </ul>
        <form method="post">
                {% csrf_token %}
                {# 订单id #}
                <input type="hidden" name="order_id" value="{{order.order_id}}">
                {# 订单中有几个商品 #}
                <input type="hidden" name="total_count" value="{{order.order_skus|length}}">
                {% for order_sku in order.order_skus %}
                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="80%">
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
                                    <li class="col02">{{order_sku.sku.name}}<em>{{order_sku.price}}/{{order_sku.sku.unite}}</em></li>
                                    <li class="col03">{{order_sku.count}}</li>
                                </ul>
                            </td>
                            <td width="20%">{{order_sku.amount}}元</td>
                        </tr>
                    </tbody>
                </table>
                <div class="site_con">
                    <input type="hidden" name="sku_{{forloop.counter}}" value="{{order_sku.sku.id}}">
                    <div class="form_group form_group2">
                        <label>评价内容：</label>
                        <textarea class="site_area" name="content_{{forloop.counter}}">{{ order_sku.comment }}</textarea>
                    </div>
                </div>
                {% endfor %}
                <input type="submit" name="" value="提交" class="info_submit">
            </form>




    </div>
{% endblock right_menu_con %}


daliyflash-day-11.20/templates/user/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_menu_con %}
    <div class="right_menu_con clearfix">
			<h3 class="common_title2">收货地址</h3>
			<div class="site_con">
				<dl>
					<div class="clearfix">
						<dt class="addr_tiltle">我的收货地址：</dt>
						<a class="add_addr" href="{% url 'user:addaddress' %}">添加新地址</a>

					</div>
                    {% if addr_num == 0 %}
                        <dd class="clearfix ">
						<div class="default clearfix">
							<span>您尚未添加地址，请先添加收货地址</span>
						</div>
					</dd>
                    {% else %}
                        {% for address in addr %}
                            <dd class="clearfix ">
                                <div class="default clearfix">
                                    {% if address.is_default%}<em>默认</em>{% endif %}
                                    <span>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone }}</span>
                                    <a href="{% url 'user:address' %}?addr_id={{ address.id }}">删除</a>
                                    <a href="{% url 'user:addaddress' %}?addr_id={{ address.id }}">编辑</a>

                                </div>
                            </dd>
                        {% endfor %}
                    {% endif %}

				</dl>
			</div>


		</div>

{% endblock right_menu_con %}
