daliyflash-day-11.20/apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartView,CartAddView,CartUpdateView,CartDelView

urlpatterns = [
    url(r'^add$',CartAddView.as_view(),name='cart_add'),
    url(r'^update$',CartUpdateView.as_view(),name='cart_update'),
    url(r'^del$',CartDelView.as_view(),name='cart_del'),
    url(r'^$',CartView.as_view(),name='cart_show'),


]

daliyflash-day-11.20/apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView,DetailView,ListView

urlpatterns = [
    url(r'^index$',IndexView.as_view(),name='index'),
    url(r'^goods/(?P<goods_id>\d+)$',DetailView.as_view(),name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list'),
]

daliyflash-day-11.20/apps/user/urls.py
from django.conf.urls import url
from apps.user import views
from django.contrib.auth.decorators import login_required
from user.views import RegisterView,ActiveView,LoginView,UserInfoView,UserOrderView,AddressView,LogoutView,AddAddressView
urlpatterns = [
    #url(r'^register$',views.register,name = 'register'),
    #url(r'^register_handle$',views.register_handle,name='register_handle'),
    url(r'^register$',RegisterView.as_view(),name = 'register'),
    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name = 'active'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout',LogoutView.as_view(),name='logout'),

   # url(r'^$',login_required(UserInfoView.as_view()),name = 'user' ),
    #url(r'^order',login_required(UserOrderView.as_view()) ,name = 'order'),
    #url(r'^address',login_required(AddressView.as_view()) ,name='address'),
    url(r'^$',UserInfoView.as_view(),name = 'user' ),
    url(r'^order/(?P<page>\d+)$',UserOrderView.as_view() ,name = 'order'),
    url(r'^address$',AddressView.as_view() ,name='address'),
    url(r'^add_address$',AddAddressView.as_view() ,name='addaddress'),

]

daliyflash-day-11.20/daliyflash/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^user/', include('user.urls', namespace='user')),  # 用户模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')),  # 订单模块
    url(r'^search', include('haystack.urls')),  # 搜索引擎
    url(r'^', include('goods.urls', namespace='goods')),  # 商品模块
]

daliyflash-day-11.20/templates/base.html
{# 首页　登录　注册#}
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    {# 网页标题内容快 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type ="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type ="text/css"  href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}

</head>
<body>
	<!-- header -->
    {# 顶部欢迎模块 #}
    {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜！</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_info fl">
					欢迎您：<em>{{ user.username }}</em>
				</div>
                <div class="login_btn fl">
				 	<span>|</span>
				 	<a href="{% url 'user:logout' %}">退出登录</a>
                </div>
                {% else  %}
				 <div class="login_btn fl">
				 	<a href="{% url 'user:login' %}">登录</a>
				 	<span>|</span>
				 	<a href="{% url 'user:register' %}">注册</a>
				 </div>
                {% endif %}
				 <div class="user_link fl">
				 	<span>|</span>
				 	<a href="{% url 'user:user' %}">用户中心</a>
				 	<span>|</span>
				 	<a href="{% url 'cart:cart_show' %}">我的购物车</a>
				 	<span>|</span>
				 	<a href="{% url 'user:order' 1 %}">我的订单</a>

				 </div>

			</div>
		</div>
	</div>
    {% endblock header_con %}
	<!-- 搜索logo -->
    {# 搜索 #}
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a class="logo fl" href="{% url 'goods:index' %}">
			<img src="{% static 'images/logo.png' %}">
		</a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input class="input_text fl" type="text" name="q" placeholder="搜索商品">
                <input class="input_btn fr" type="submit" name="" value="搜索">
            </form>
		</div>

		<div class="guest_cart fr">
			<a  href = "{% url 'cart:cart_show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl">{{ cart_count }}</div>
		</div>
	</div>
    {% endblock search_bar %}
	<!-- 主菜单 -->
    {# 主体部分 #}
    {% block body %}

    {% endblock body %}

	<!-- 版权信息 -->
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2019 **********有限公司 All Rights Reserved</p>
		<p>电话：0*******888    ************</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}

</body>
</html>

daliyflash-day-11.20/templates/base_detail_list.html
{# 商品列表，商品详情 #}
{% extends  'base.html' %}
{% load staticfiles %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for goods_type in goods_types %}
					<li><a href="{% url 'goods:list' goods_type.id 1 %}" class="{{ goods_type.logo }}">{{ goods_type.name }}</a></li>
                    {% endfor %}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {# 列表内容　详情内容 #}
    {% block main_content%}
    {% endblock main_content %}
{% endblock body %}

daliyflash-day-11.20/templates/base_no_cart.html
{# 用户中心,提交订单 #}
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
    <div class="search_bar clearfix">
		<a class="logo fl" href="{% url 'goods:index' %}">
			<img src="{% static 'images/logo.png' %}">
		</a>
		<div class="sub_page_name fl"><span>|</span>{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
            <form action="/search" method="get">
                <input class="input_text fl" type="text" name="q" placeholder="搜索商品">
                <input class="input_btn fr" type="submit" name="" value="搜索">
            </form>

		</div>
	</div>
{% endblock search_bar %}

daliyflash-day-11.20/templates/base_user_center.html
{# 用户中心３页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}
    天天生鲜-用户中心
{% endblock title %}
{% block page_title %}
    用户中心
{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if  page == 'user' %}class="active"{% endif %}>.个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if  page == 'order' %}class="active"{% endif %}>.全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if  page == 'address' %}class="active"{% endif %}>.收货地址</a></li>
			</ul>
		</div>
        {% block right_menu_con %}
		{% endblock right_menu_con %}

	</div>
{% endblock body %}

daliyflash-day-11.20/templates/static_base.html
{# 首页　登录　注册#}
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    {# 网页标题内容快 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type ="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type ="text/css"  href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}

</head>
<body>
	<!-- header -->
    {# 顶部欢迎模块 #}
    {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜！</div>
			<div class="fr">

				 <div class="login_btn fl">
				 	<a href="{% url 'user:login' %}">登录</a>
				 	<span>|</span>
				 	<a href="{% url 'user:register' %}">注册</a>
				 </div>
				 <div class="user_link fl">
				 	<span>|</span>
				 	<a href="{% url 'user:user' %}">用户中心</a>
				 	<span>|</span>
				 	<a href="#">我的购物车</a>
				 	<span>|</span>
				 	<a href="#">我的订单</a>

				 </div>

			</div>
		</div>
	</div>
    {% endblock header_con %}
	<!-- 搜索logo -->
    {# 搜索 #}
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a class="logo fl" href="{% url 'goods:index' %}">
			<img src="{% static 'images/logo.png' %}">
		</a>
		<div class="search_con fl">
			<input class="input_text fl" type="text" name="" placeholder="搜索商品">
			<input class="input_btn fr" type="button" name="" value="搜索">
		</div>

		<div class="guest_cart fr">
			<a  href = "#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl">{{ cart_count }}</div>
		</div>
	</div>
    {% endblock search_bar %}
	<!-- 主菜单 -->
    {# 主体部分 #}
    {% block body %}

    {% endblock body %}

	<!-- 版权信息 -->
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2019 **********有限公司 All Rights Reserved</p>
		<p>电话：0*******888    ************</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}

</body>
</html>

daliyflash-day-11.20/templates/static_index.html
{% extends 'static_base.html' %}
{% load staticfiles %}
{% block title %}
    天天生鲜-首页
{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src = "{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
    <!-- 主菜单 -->
	<div class="main_menu_con">
		<div class="center_con02">
			<h2>全部商品分类</h2>
			<ul>
				<li><a href="#">首页</a></li>
				<li><a href="#">手机生鲜</a></li>
				<li><a href="#">抽奖</a></li>
			</ul>
		</div>
	</div>

	<!-- 二级菜单 幻灯片 广告 -->
	<div class="center_con03">

			<ul class="sub_menu_con fl">
                {% for goods_type in goods_types %}
				    <li><a href="#model0{{ forloop.counter }}" class="{{ goods_type.logo }}">{{ goods_type.name }}</a></li>

				{% endfor %}
			</ul>
		<div class="slide_con fl">
			<ul class="slide">
                {% for index_goods_banner in index_goods_banners %}
				    <li><a href="#"><img src="{{ index_goods_banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>

			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points">
				<!-- <li class="active"></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li> -->
			</ul>

		</div>
		<div class="advs fl">
            {% for index_promotion_banner in index_promotion_banners %}
			    <a href="#"><img src="{{ index_promotion_banner.image.url }}" alt="广告图片"></a>
			{% endfor %}
		</div>
	</div>

	<!-- 公共模块 -->
    {% for goods_type in goods_types  %}
	    <div class="common_model">
            <div class="common_title_con">
                <h3 >{{ goods_type.name }}</h3>
                <ul >
                    {% for title_banner in goods_type.title_banners %}
                        <li><a href="#">{{ title_banner.sku.name }}</a></li>
                    {% endfor %}
                </ul>
                <a href="#" class="more">查看更多 &gt;&gt;</a>
            </div>
            <div class="goods_banner fl" >
                <a href="#"><img src="{{ goods_type.image.url }}" alt="水果"></a>
            </div>
            <ul class="goods_list fl" >
                {% for image_banner in goods_type.image_banners %}
                    <li>
                        <h4>{{ image_banner.sku.name }}</h4>
                        <a href="#"><img src="{{ image_banner.sku.image.url }}" alt="草莓"></a>
                        <div class="price">¥ {{ image_banner.sku.price }}</div>
                    </li>
                {% endfor %}

		    </ul>
	    </div>
    {% endfor %}

{% endblock body %}
